rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'

# Commented paths are no longer needed since we use
# Django's registration app now.
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('add_category/', views.add_category, name="add_category"),
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('restricted/', views.restricted, name='restricted'),
    path('search/', views.search, name='search'),
    path('like_category/', views.LikeCategoryView.as_view(), name='like_cateogory'),
    path('suggest/', views.CategorySuggestionView.as_view(), name='suggest'),
    #path('register/', views.register, name="register"),
    #path('login/', views.user_login, name='login'),
    #path('logout/', views.user_logout, name='logout')
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')), # This line maps any URLs starting with 'rango/' to be handled by rango.
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):

    NAME_MAX_LENGTH = 128

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

    name = models.CharField(max_length=NAME_MAX_LENGTH, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(blank=True, unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

class Page(models.Model):

    TITLE_MAX_LENGTH = 128
    URL_MAX_LENGTH = 200
    
    def __str__(self):
        return self.title

    title = models.CharField(max_length=TITLE_MAX_LENGTH)
    url = models.URLField(max_length=URL_MAX_LENGTH)
    views = models.IntegerField(default=0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username
    

rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import Category, Page, UserProfile

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=Category.NAME_MAX_LENGTH, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=Page.TITLE_MAX_LENGTH, help_text="Please enter the title of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    url = forms.URLField(max_length=Page.URL_MAX_LENGTH, help_text="Please enter the URL of the page.")

    class Meta:
        model = Page
        exclude = ('category',)


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())    

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)


class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('website', 'picture',)

rango/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.conf import settings
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from rango.models import Category, Page
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm
from rango.bing_search import run_query
from datetime import datetime
from django.views.generic.base import View
from django.utils.decorators import method_decorator
from rango.helpers import get_category_list

def get_server_side_cookie(request, cookie, default_val=0):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, "visits","1"))

    last_visit_cookie = get_server_side_cookie(request, "last_visit", str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie
    
    request.session["visits"] = visits


def index(request):
    category_list = Category.objects.order_by('-likes')[:5]

    context_dict = {}
    context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    context_dict['categories'] = category_list

    # The code for displaying the top viewd pages without using order_by is this:
    # pages = [page for page in sorted(Page.objects.all(), key= lambda x: x.views, reverse=True)[:5]]

    pages = Page.objects.order_by('-views')[:5]
    context_dict['pages'] = pages

    visitor_cookie_handler(request)

    response = render(request, 'rango/index.html', context=context_dict)
    return response


def about(request):
    visitor_cookie_handler(request)
    visits = request.session['visits']
    context_dict = {'MEDIA_URL' : settings.MEDIA_URL, 'visits':visits}
    return render(request, 'rango/about.html', context=context_dict)


def show_category(request, category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        context_dict['category'] = category
        context_dict['pages'] = pages

    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None

    return render(request, 'rango/category.html', context=context_dict)

@login_required
def add_category(request):
    form = CategoryForm()
    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return redirect(reverse('rango:index'))
        else:
            print(form.errors)
    return render(request, 'rango/add_category.html', {'form':form})

@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None
    
    if category is None:
        return redirect('/rango/')

    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)
    
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return redirect(reverse('rango:show_category', kwargs={'category_name_slug':category_name_slug}))
        else:
            print(form.errors)
        
    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)

@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')

def search(request):
    query = ''
    result_list = []

    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:
            result_list = run_query(query)
    
    return render(request, 'rango/search.html', context={'result_list':result_list,'query_text':query})

class LikeCategoryView(View):
    @method_decorator(login_required)
    def get(self, request):
        category_id = request.GET['category_id']

        try:
            category = Category.objects.get(id=int(category_id))
        except Category.DoesNotExist:
            return HttpResponse(-1)
        except ValueError:
            return HttpResponse(-1)

        category.likes += 1
        category.save()

        return HttpResponse(category.likes)

class CategorySuggestionView(View):
    def get(self, request):
        suggestion = request.GET.get('suggestion','')

        category_list = get_category_list(8, suggestion)

        if not category_list:
            category_list = Category.objects.order_by('-likes')

        return render(request, 'rango/categories.html', {'categories':category_list})




# COMMENTED BLOCKS OF CODE IS THE MANUAL WAY FOR PROVIDING THE FUNCTIONALITIES.
# INSTEAD, NOW THE REGISTRATION APP PROVIDED BY DJANGO IS USED.
# def register(request):
#     registered = False

#     if request.method == 'POST':
#         user_form = UserForm(request.POST)
#         profile_form = UserProfileForm(request.POST)

#         if user_form.is_valid() and profile_form.is_valid():
#             user = user_form.save()
#             user.set_password(user.password)
#             user.save()

#             profile = profile_form.save(commit=False)
#             profile.user = user

#             if 'picture' in request.FILES:
#                 profile.picture = request.FILES['picture']

#             profile.save()
#             registered = True
#         else:
#             print(user_form.errors, profile_form.errors)
#     else:
#         user_form = UserForm()
#         profile_form = UserProfileForm()

#     return render(request, 'rango/register.html', context={'user_form':user_form, 'profile_form':profile_form, 'registered':registered})


# def user_login(request):
#     if request.method == 'POST':
#         username = request.POST.get('username')
#         password = request.POST.get('password')

#         user = authenticate(username=username, password=password)

#         if user:
#             if user.is_active:
#                 login(request, user)
#                 return redirect(reverse('rango:index'))
#             else:
#                 return HttpResponse("Your Rango account is disabled.")

#         else:
#             print(f"Invalid login details: {username}, {password}")
#             return HttpResponse("Invalid login details supplied.")
#     else:
#         return render(request, 'rango/login.html')


# @login_required
# def user_logout(request):
#     logout(request)
#     return redirect(reverse('rango:index'))

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    About Rango
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Rango says...</h1>
        <div>
            here is the about page.<br />
            <strong>This tutorial has been put together by Spheniscus Demersus.</strong>
        </div>
    </div>
</div>

    <div>
        Visits: {{ visits }}
    </div>

    <button class="btn btn-primary"
            onclick="alert('You clicked the button using inline JavaScript.');">
            Click me - I run on vanilla JavaScript!
    </button>
    <button class="btn btn-primary"
            id="about-btn">
            Click me - I'm using jQuery!
    </button>
    <br></br>

    <p>This is some random paragraph for demonstration purposes.</p>

    <div id="msg">Hello! I'm a further example for jQuery testing.</div>

    <div>
        <img src="{% static 'images/rango.jpg'%}" alt="Picture of Rango" />
    </div>
    <div>
        <img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a Cat." />
    </div>
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
Add a Category
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Add a Category</h1>
        <div class="row">
            <div>
                <form role="form" id="category_form" method="post" action="{% url 'rango:add_category' %}">
                    {% csrf_token %}

                    {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                    {% endfor %}

                    {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}
                    {{ field }}
                    <div class="p-2"></div>
                    {% endfor %}
                    <br />
                    <button class="btn btn-primary" type="submit" name="submit">
                        Add Category
                    </button>
                    <div class="p-5"></div>

                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/rango/add_page.html
{% extends "rango/base.html" %}
{% block title %}Add Page{% endblock %}
{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Add a Page to {{category.name}}</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <form role="form" id="page_form" method="post" action="{% url 'rango:add_page' category.slug %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
            {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}<br />
            {{ field }}<br />
            <div class="p-2"></div>
            {% endfor %}
            <br />
            <button class="btn btn-primary" type="submit" name="submit">
                Add Page
            </button>
            <div class="p-5"></div>
        </form>
    </div>
</div>
{% endblock %}

templates/rango/base-old.html
<!DOCTYPE html>

{% load staticfiles %}
{% load rango_template_tags %}

<html>
    <head>
        <meta charset="UTF-8" />
        <title>
            Rango - 
            {% block title_block %}
                How to Tango with Django!
            {% endblock %}
        </title>
    </head>

    <body>
        <!-- Page specific content goes here. -->
        <div>
            {% block body_block %}
            {% endblock %}
        </div>

        <div>
            {% block sidebar_block %}
                {% get_category_list category %}
            {% endblock %}
        </div>

        <hr />
        <div>
            <ul>
                {% if user.is_authenticated %}
                <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                <li><a href="{% url 'auth_logout' %}?next={% url 'rango:index' %}">Logout</a></li>
                <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
                <li><a href="{% url 'auth_password_change' %}">Change Password</a></li>
                {% else %}
                <li><a href="{% url 'registration_register' %}">Sign Up</a></li>
                <li><a href="{% url 'auth_login' %}">Login</a></li>
                {% endif %}
                <li><a href="{% url 'rango:about' %}">About</a></li>
                <li><a href="{% url 'rango:index' %}">Index</a></li>
            </ul>
        </div>
    </body>
</html>

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <title>
        Rango - {% block title_block %}How to Tango with Django!{% endblock %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0">
            <a class="navbar-brand p-2" href="{% url 'rango:index' %}">Rango</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item"><a class="nav-link" href="{% url 'rango:index' %}">Home</a></li>
                    <li class="nav-item "><a class="nav-link" href="{% url 'rango:about' %}">About</a></li>
                    <li class="nav-item"><a class ="nav-link" href="{% url 'rango:search' %}">Search</a></li>
                    {% if user.is_authenticated %}
                    <li class="nav-item "><a class="nav-link" href="{% url 'rango:restricted' %}">Restricted</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'rango:add_category' %}">Add Category</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'auth_password_change' %}">Change Password</a>
                    </li>
                    {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'registration_register' %}">Register Here</a>
                    </li>
                    <li class="nav-item "><a class="nav-link" href="{% url 'auth_login' %}">Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    <div class="container-fluid">
        <div class="row">
            <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                <div class="w-75 ml-3">
                    <input type="search"
                            id="search-input"
                            class="form-control ds-input"
                            placeholder="Search..."/>
                </div>
                <div class="sidebar-sticky" id="categories-listing">
                    {% block sidebar_block %}
                        {% get_category_list category %}
                    {% endblock %}
                </div>
            </nav>

            <main role="main" class="col-md-9  ml-sm-auto col-lg-10 px-4">
                {% block body_block %}{% endblock %}

                <!-- FOOTER -->
                <footer>
                    <p class="float-right"><a href="#">Back to top</a></p>
                    <p>&copy; 2020 Tango With Django 2 &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a>
                    </p>
                </footer>
            </main>
        </div>
    </div>

    <!-- Bootstrap core JavaScript -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/rango-jquery.js' %}"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/rango-ajax.js' %}"
        crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
    <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script>
</body>

</html>

templates/rango/categories.html
<ul class="nav flex-column">
    {% if categories %}
        {% for c in categories %}
            {% if c == current_category %}
                <li class="nav-item">
                    <strong>
                        <a class="nav-link active" href="{% url 'rango:show_category' c.slug %}">
                            <span data-feather="archive"></span>{{ c.name }}
                        </a>
                    </strong>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'rango:show_category' c.slug %}">
                        <span data-feather="archive"></span>{{ c.name }}
                    </a>
                </li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li class="nav-item">There are no categories present.</li>
    {% endif %}
</ul>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
    {% if category %}
        <h1 class="jumbotron-heading">{{ category.name }}</h1>
        <div>
            <strong id="like_count">{{ category.likes }}</strong> likes
            {% if user.is_authenticated %}
                <button id="like_btn"
                        data-categoryid="{{ category.id }}"
                        class="btn btn-primary btn-sm"
                        type="button">
                    <span data-feather="thumbs-up"></span>
                    Like Category
                </button>
            {% endif %}
        </div>
        {% if pages %}
            <ul>
                {% for page in pages %}
                    <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>No pages currently in category.</strong>
        {% endif %}
        {% if user.is_authenticated %}
            <a href="{% url 'rango:add_page' category.slug %}">Add Page</a> <br />
        {% endif %}
    {% else %}
        The specified category does not exist.
    {% endif %}
    </div>
</div>
{% endblock %}

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
Homepage
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Rango says...</h1>
        <div>
            <h2 class="h2">
                {% if user.is_authenticated %}
                howdy {{ user.username }}!
                {% else %}
                hey there partner!
                {% endif %}
            </h2>
            <strong>{{ boldmessage }}</strong>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="card mb-6">
                <div class="card-body">
                    <h2>Most Liked Categories</h2>
                    <p class="card-text">
                        {% if categories %}
                    <ul class="list-group">
                        {% for category in categories %}
                        <li class="list-group-item">
                            <a href="{% url 'rango:show_category' category.slug %}">
                                {{ category.name }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                    {% else %}
                    <strong>There are no categories present.</strong>
                    {% endif %}
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card mb-6">
                <div class="card-body">
                    <h2>Most Viewed Pages</h2>
                    <p class="card-text">
                        {% if pages %}
                    <ul class="list-group">
                        {% for page in pages %}
                        <li class="list-group-item">
                            <a href="{{ page.url }}">{{ page.title }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                    {% else %}
                    <strong>There are no pages present.</strong>
                    {% endif %}
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

<div>
    <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
</div>
{% endblock %}

templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
<!-- THIS TEMPLATE IS NO LONGER USED -->
{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
    <h1>Login to Rango</h1>
    <form id="login_form" method="post" action="{% url 'rango:login' %}">
        {% csrf_token %}
        Username: <input type="text" name="username" value="" size="50" />
        <br />
        Password: <input type="password" name="password" value="" size="50" />
        <br />
        <input type="submit" value="submit" />
    </form>
{% endblock %}

templates/rango/register.html
<!-- THIS TEMPLATE IS NO LONGER USED -->
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
    <h1>Register for Rango</h1>
    {% if registered %}
        Rango says: <strong>thank you for registering!</strong>
        <a href="{% url 'rango:index' %}">Return to the homepage.</a><br />
    {% else %}
        Rango says: <strong>register here!</strong><br />
        <form id="user_form" method="POST" action="{% url 'rango:register' %}" enctype="multipart/form-data">
            {% csrf_token %}

            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <input type="submit" name="submit" value="Register" />
        </form>
    {% endif %}
{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Restricted Page
{% endblock %}

{% block body_block %}
    Since you're logged in, you can see this text!
{% endblock %}

templates/rango/search.html
{% extends 'rango/base.html' %}

{% block title_block %}
    Search
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Search with Rango</h1>
    </div>
</div>

<div>
    <form class="form-inline" id="user-form" method="POST" action="{% url 'rango:search' %}">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" type="text" size="50" name="query" id="query" value="{{ query_text }}"/>
        </div>
        
        <button class="btn btn-primary" type="submit" name="submit">Search</button>
    </form>
</div>

<div>
    {% if result_list %}
    <h2>Results</h2>

    <div class="list-group">
        {% for result in result_list %}
            <div class="list-group-item">
                <h3 class="list-group-item-heading">
                    <a href="{{ result.link }}">{{ result.title|safe|escape }}</a>
                </h3>
                <p class="list-group-item-text">{{ result.summary|safe|escape }}</p>
            </div>
        {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock %}